export default [
  {
    id: "FAEAFEE",
    name: "Nome do Produto",
    type: "Tipo 1",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "VASD2F",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "VDZVEG",
    name: "Nome do Produto",
    type: "Tipo 1",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "KJKDS2",
    name: "Nome do Produto",
    type: "Tipo 2",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
  {
    id: "AW2DWS",
    name: "Nome do Produto",
    type: "Tipo 3",
    price: 5000,
  },
];
